apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-addons
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s-addons
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - git@github.com:msi-cloud-it/MCAP_Addons.git
  - git@github.com:msi-cloud-it/MCAP_Sandbox.git
  - "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'