apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{lower .Values.clusterName }}-argocd-app-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.server }}
    namespace: argocd
  project: {{ .Values.project }}
  source:
    path: {{ .Values.path }}
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - {{ .Values.valuesFile }}
      values: |
        istiogateway:
            loadbalancername: {{ .Values.loadbalancername }}
            loadbalanceradditionaltags: {{ .Values.loadbalanceradditionaltags }}
        argocd:
            url: {{ .Values.argocdurl }}
        server: {{ .Values.server }}
        cluster_type: {{ .Values.cluster_type }}    
        clusterName: {{ .Values.clusterName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 120s
        factor: 2 
        maxDuration: 900s
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground